/**
 * Base Point — internal data model for payment requests.
 *
 * These types describe records owned by Base Point itself (stored in the
 * MVP via `localStorage`, later swappable for Supabase). They are NOT the
 * same as the Base Pay SDK's payment-status type — see `lib/basePay.ts`
 * for that.
 *
 * Base Point now runs on Base mainnet:
 *  - `network` is fixed to `"base"`.
 *  - `chainId` is fixed to `8453`.
 *  - There is no field for testnet, balances, or external explorer data.
 */

import type { CHAIN_ID, NETWORK_NAME } from "@/lib/network";

/**
 * Lifecycle of a Base Point payment request.
 *
 * Distinct from the SDK's `PaymentStatusType` (`pending | completed |
 * failed | not_found`). Translation rules used by the public payment page:
 *
 *   SDK `not_found`  -> internal `processing` (transaction not yet visible)
 *   SDK `pending`    -> internal `processing` (submitted, awaiting confirm)
 *   SDK `completed`  -> internal `completed`
 *   SDK `failed`     -> internal `failed`
 */
export type PaymentRequestStatus =
  | "pending" // created, customer has not yet paid
  | "processing" // pay() submitted, awaiting on-chain confirmation
  | "completed" // confirmed on-chain
  | "failed"; // user cancelled or chain reported failure

export interface PaymentRequest {
  /** Local UUID, used as the slug in /pay/[id]. */
  id: string;

  /** Merchant wallet that should receive the USDC. */
  recipient: `0x${string}`;

  /**
   * USDC amount as a decimal string (e.g. "10.50"). Stored as a string to
   * avoid float drift; this is also the format the Base Pay SDK accepts.
   *
   * For itemised receipts this equals `quantity * unitPriceUsdc` rounded
   * to 6 USDC decimals. The form computes it server-side via viem so we
   * never touch JavaScript floats.
   */
  amountUsdc: string;

  /** Free-form merchant note (private). May be the empty string. */
  note: string;

  /** Current lifecycle state of this request. */
  status: PaymentRequestStatus;

  /**
   * On-chain identifier for the payment.
   *  - For the Base Pay path: the userOp hash returned by `pay()`.
   *  - For the wallet path: the EVM transaction hash returned by
   *    `writeContract(...transfer)`.
   *
   * `paidVia` (below) tells you which path was used.
   */
  paymentId?: string;

  /**
   * Which payment path was used to settle this request. Set on the
   * optimistic write that flips the record to `processing`.
   */
  paidVia?: "base-pay" | "wallet";

  /** Last error message surfaced to the customer, if any. */
  errorMessage?: string;

  /** Network metadata — pinned to Base mainnet. */
  network: typeof NETWORK_NAME;
  chainId: typeof CHAIN_ID;

  /** Epoch ms; when the request was created. */
  createdAt: number;
  /** Epoch ms; when `pay()` first resolved. */
  submittedAt?: number;
  /** Epoch ms; when a terminal status was reached. */
  settledAt?: number;

  // ----- Receipt / POS metadata --------------------------------------
  // Everything below is optional so existing records (created before
  // these fields existed) continue to round-trip through the storage
  // layer without being silently dropped by the type guard.

  /**
   * Human-readable receipt id, e.g. `BP-20260525-A1F3`. Generated by
   * the storage layer at create time (not user-supplied) and used as
   * the slug for the public `/receipt/[id]` page.
   */
  receiptId?: string;

  /** Merchant display name, e.g. "Acme Coffee". */
  merchantName?: string;

  /** Item / service name, e.g. "Latte". */
  itemName?: string;

  /**
   * Quantity of items. Whole numbers only in the MVP — keeps the
   * `quantity * unitPriceUsdc` total math obvious and float-free.
   */
  quantity?: number;

  /**
   * Per-item price in USDC, decimal-string form (same conventions as
   * `amountUsdc`).
   */
  unitPriceUsdc?: string;

  /**
   * Optional label printed on the customer-facing receipt, e.g.
   * "Table 5" or "Order #1234". Distinct from the private `note`.
   */
  customerLabel?: string;

  /**
   * Canonical public receipt URL when known. The UI may also compute
   * one from `receiptId` + `window.location.origin`; this field exists
   * so a future Supabase adapter can persist a single absolute URL.
   */
  receiptUrl?: string;
}

/**
 * Shape accepted by `PaymentStore.create`. The store fills in `id`,
 * `receiptId`, `status`, `createdAt`, `network`, and `chainId` itself
 * so callers cannot tag a record with the wrong network or spoof a
 * receipt id.
 */
export type CreatePaymentRequestInput = Pick<
  PaymentRequest,
  "recipient" | "amountUsdc" | "note"
> &
  Partial<
    Pick<
      PaymentRequest,
      | "merchantName"
      | "itemName"
      | "quantity"
      | "unitPriceUsdc"
      | "customerLabel"
    >
  >;
